import React from 'react'

const Data = [
            {
                id:1,
                title:'top',
                category:'top',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
               followers:'10k-20k',
                engagement:4837,
                age:'18+',
                residency:'india',
            },
            
            {
                id:2,
                title:'top',
                category:'top',
                imgSrc: './images/card2.png',
                description:'this is a beatutiful top',
              followers:'20k-40k',
                engagement:4837,
                age:'20+',
                residency:'india',
            },
            {
                id:3,
                title:'top',
                category:'top',
                imgSrc: './images/card3.png',
                description:'this is a beatutiful top',
              followers:'90k-100k',
                engagement:4837,
                age:'25+',
                residency:'india',
            },
            {
                id:4,
                title:'shoes',
                category:'shoes',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
              followers:'40k-60k',
                engagement:4837,
                age:'18+',
                residency:'india',
            },
            {
                id:5,
                title:'shoes',
                category:'shoes',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
              followers:'80k-85k',
                engagement:4837,
                age:'20+',
                residency:'india',
            },
            {
                id:6,
                category:'top',
                title:'top',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
              followers:'90-95',
                engagement:4837,
                age:'20+',
                residency:'india',
            },
            {
                id:7,
                title:'top',
                category:'top',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
                followers:'90-95',
                engagement:4837,
                age:'18+',
                residency:'india',
            },
            {
                id:8,
                title:'shoes',
                category:'shoes',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
                followers:'90-95',
                engagement:4837,
                age:'20+',
                residency:'india',
            },
            {
                id:9,
                title:'pant',
                category:'pant',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
                followers:'90-95',
                engagement:4837,
                age:'20+',
                residency:'india'
            },
            {
                id:10,
                category:'pant',
                title:'pant',
                imgSrc: './images/card1.png',
                description:'this is a beatutiful top',
                followers:'90-95',
                engagement:4837,
                age:'25+',
                residency:'India',
            },
    ];


export default Data